


class ___FILEBASENAMEASIDENTIFIER___ {
    
}

protocol ___FILEBASENAMEASIDENTIFIER___Type: class {

}

// MARK: - ___FILEBASENAMEASIDENTIFIER___Type
extension ___FILEBASENAMEASIDENTIFIER___: ___FILEBASENAMEASIDENTIFIER___Type {

}

/**
COPY PASTE INTO ASSEMBLY

container.register(___FILEBASENAMEASIDENTIFIER___Type.self) { _ in
   return ___FILEBASENAMEASIDENTIFIER___()
} 

*/
